Dataset:
  type: CIFAR10
  data_home: "/home/aistudio/data"
  Train:
    transforms:
    - !RandomCrop
      size: 32
      padding: 4
      fill: 128
    - !RandomHorizontalFlip {}
    # - !CIFAR10Policy {}
    - !ToTensor {}
    - !Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.247, 0.243, 0.261]
    # - !Cutout
    #   n_holes: 1
    #   length: 16
    batch_size: 512
    shuffle: True
    pin_memory: False
    num_workers: 2
  Test:
    transforms:
    - !ToTensor {}
    - !Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.247, 0.243, 0.261]
    batch_size: 1024
    num_workers: 2


Model: WideResnet

WideResnet:
  num_filters: 16
  k: 10
  num_stack: 3
  num_basic_block: 4
  kernel_size: 3
  num_classes: 10

Optimizer:
  type: SGD
  lr: 0.4
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

LRScheduler:
  type: CosineAnnealingLR
  # milestones: [999999, 9999999, 99999999]
  # gamma: 0.2
  T_max: 200
  eta_min: 0
  warmup: 5
  warmup_eta_min: 0.04

# Mixup:
#   alpha: 1.0

# label_smooth: 0.1

benchmark: True
seed: 0
save_path: "/home/aistudio/work/checkpoints/CIFAR10-WRN-28-10-origin"
epochs: 200
eval_freq: 5
save_freq: 5