Dataset:
  type: CIFAR10
  data_home: "/home/aistudio/work/datasets/CIFAR10"
  Train:
    transforms:
    - !RandomCrop
      size: 32
      padding: 4
      fill: 128
    - !RandomHorizontalFlip {}
    # - !CIFAR10Policy {}
    - !ToTensor {}
    - !Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.247, 0.243, 0.261]
    # - !Cutout
    #   n_holes: 1
    #   length: 16
    batch_size: 1536
    shuffle: True
    pin_memory: False
    num_workers: 2
    use_process: False
  Test:
    transforms:
    - !ToTensor {}
    - !Normalize
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.247, 0.243, 0.261]
    batch_size: 1024
    num_workers: 2
    use_process: False


Model: PreActResNet

PreActResNet:
  depth: 28
  k: 10
  use_se: True

Optimizer:
  type: SGD
  lr: 1.2
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

LRScheduler:
  type: CosineAnnealingLR
  T_max: 200
  eta_min: 0.001
  warmup: 10
  warmup_eta_min: 0.1

# Mixup:
#   alpha: 1.0

# label_smooth: 0.1

fp16: True
benchmark: True
seed: 0
save_path: "/home/aistudio/work/checkpoints/CIFAR10-WRN"
epochs: 200
eval_freq: 10
save_freq: 100